#%% md
# Scale Invariance Atlas
#
# A living, visual summary of the Scale Invariance Framework (Systems 1–9).
#
# Central Principle: $P(S; H, T) = P(S; \alpha H, \alpha T),\; \forall\, \alpha>0$
#
# This notebook runs core experiments and assembles publication-ready visualizations.

#%%
# Setup
import os
import numpy as np
import matplotlib.pyplot as plt
try:
    from IPython.display import Image, display  # type: ignore
except Exception:  # pragma: no cover - fallback when IPython not present
    Image = None
    def display(*args, **kwargs):
        # Minimal fallback: print file paths if images would be displayed
        for arg in args:
            try:
                print(getattr(arg, 'filename', arg))
            except Exception:
                print(arg)

# Core experiments
from scale_invariance import run_scale_invariance_test, quantify_divergence
from materials_invariance import (
    create_sword_system,
    create_semiconductor_system,
    run_materials_invariance_test,
)
from tpu_benchmark import benchmark_suite

# Visualization helpers
from viz.scale_invariance_plots import generate_scale_invariance_animation
from viz.materials_plots import generate_scale_span_visualization
from viz.tpu_benchmark_plots import generate_tis_ladder_animation

# Ensure output directory exists
os.makedirs("viz/publication", exist_ok=True)

# Style
plt.rcParams["figure.figsize"] = (8, 5)
plt.rcParams["figure.dpi"] = 120

#%% md
# ## Priority 1: Scale Invariance Proof (Systems 1–3)
# We demonstrate that scaling energy and temperature together leaves the distribution invariant.

#%%
# Run the experiment and show overlay plot inline
N, alpha, T0, num_samples, seed = 5, 2.0, 1.0, 50000, 42
P_orig, P_scaled_E, P_test, params = run_scale_invariance_test(
    N=N, alpha=alpha, T0=T0, num_samples=num_samples, seed=seed
)

# Normalize and compute divergences
def _nz(x):
    x = np.maximum(np.asarray(x), 1e-15)
    return x / x.sum()

P_orig, P_scaled_E, P_test = map(_nz, (P_orig, P_scaled_E, P_test))
D_proof = quantify_divergence(P_orig, P_test)
D_ctrl = quantify_divergence(P_orig, P_scaled_E)

# Overlay visualization
fig, ax = plt.subplots()
states = np.arange(len(P_orig))
ax.bar(states, P_orig, alpha=0.5, label="Original (W,H,T)", color="#1f77b4")
ax.plot(
    states,
    P_test,
    "o-",
    color="#2ca02c",
    linewidth=2,
    markersize=5,
    label="Scaled (αW,αH,αT)",
)
ax.plot(
    states,
    P_scaled_E,
    "s--",
    color="#d62728",
    linewidth=1,
    markersize=4,
    label="Control (αW,αH,T)",
)
ax.set_xlabel("State Index")
ax.set_ylabel("Probability")
ax.set_title("Scale Invariance Validation")
ax.legend()
ax.grid(alpha=0.3)
ax.text(
    0.02,
    0.98,
    f"D_KL(orig||test) = {D_proof:.6f}\nD_KL(orig||ctrl) = {D_ctrl:.6f}",
    transform=ax.transAxes,
    va="top",
    bbox=dict(boxstyle="round", facecolor="lightgreen", alpha=0.8),
)
plt.show()

# Generate animation GIF and display
gif_path = generate_scale_invariance_animation(
    output_path="viz/publication/scale_invariance_proof.gif",
    N=N,
    alpha=alpha,
    T0=T0,
    num_samples=num_samples,
    seed=seed,
)
if Image:
    display(Image(filename=gif_path))
else:
    print(gif_path)

#%% md
# ## Priority 2: System 8 — Scale Span (Atoms to Alloys)
# We show scale invariance spanning nine orders of magnitude.

#%%
span_info = generate_scale_span_visualization(
    output_path="viz/publication/fig2_materials_span.png",
    T_semi=800.0,
    T_sword=1000.0,
    alpha=2.0,
)
if Image:
    display(Image(filename=span_info["output_path"]))
else:
    print(span_info["output_path"])
span_info

#%% md
# ## Priority 3: System 9 — Thermodynamic Integrity Score (TIS)
# Benchmark suite and quality ladder.

#%%
tis_gif = generate_tis_ladder_animation(
    output_path="viz/publication/tis_quality_ladder.gif",
    N=5,
    T0=1.0,
    alpha=2.0,
    num_samples=20000,
    seed=42,
)
if Image:
    display(Image(filename=tis_gif))
else:
    print(tis_gif)

#%% md
# ## Priority 4: RG Fixed Point Visualization
# Hardware at/away from the RG fixed point (see pre-generated animation).

#%%
# Display existing RG flow animation if available
rg_path_candidates = [
    "viz/publication/rg_flow.gif",
    "viz/viz/publication/rg_flow.gif",
]
for p in rg_path_candidates:
    if os.path.exists(p):
        if Image:
            display(Image(filename=p))
        else:
            print(p)
        break
else:
    print(
        "RG flow animation not found. See viz/rg_analysis_plots.py for generation options."
    )

#%% md
# ## Advanced Visualizations (Gallery)
# Links to additional figures and animations generated by the codebase.

#%%
gallery = [
    "viz/viz/publication/quenching.gif",
    "viz/viz/publication/vapor_deposition.gif",
    "viz/viz/publication/scale_invariance_proof.gif",
    "viz/viz/publication/tis_quality_ladder.gif",
    "viz/viz/viz/publication/unhinged_graycode_trails.gif",
    "viz/viz/viz/publication/unhinged_probability_carpet.gif",
    "viz/viz/viz/publication/unhinged_scale_islands.gif",
    "viz/viz/viz/publication/unhinged_scale_waves.gif",
]
for path in gallery:
    if os.path.exists(path):
        if Image:
            display(Image(filename=path))
        else:
            print(path)
    else:
        print("Missing:", path)
